app/models/Products.php
<?php

namespace App\Models;

use Core\Database\Model;

class Products extends Model
{
    protected static $table = 'products';

    const ID_GENDER_MALE = 1;
    const ID_GENDER_FEMALE = 2;
    const ID_GENDER_UNISEX = 3;

    public $id;

    public $name;

    public $gender;

    public $price;

    public $category_id;

    public $deleted;

    public $created_at;

    public static function getGenders()
    {
        return [
          'male' => self::ID_GENDER_MALE,
          'female' => self::ID_GENDER_FEMALE,
          'unisex' => self::ID_GENDER_UNISEX
        ];
    }
}

app/controllers/ProductsController.php
<?php

namespace App\Controllers;

use App\Controllers\FrontendController;
use App\Models\Orders;
use App\Models\Products;
use App\Models\Categories;
use Core\Database\Database;
use Core\Paginator;

class ProductsController extends FrontendController
{
    public function index()
    {
        $categories = Categories::buildMenu('products');
        $products = [];
        $pages = null;

        $currentCategory = null;

        if ($currentCategory = $this->request->get('cat')) {
            $children = Categories::getChildrenIdString($currentCategory);
            $where = "WHERE category_id IN ({$children}) ";
            // ToDo more filters
            if ($gender = $this->request->get('gender')) {
                $where .= "AND gender = {$gender}";
            }

            $pages = new Paginator(Products::query("SELECT COUNT (*) FROM products {$where}")->first()->count);
            $products = Database::connection('sphinx')->query("SELECT * FROM products {$where} LIMIT {$pages->offset}, {$pages->perPage}")->results();
        }

        $this->view->render('frontend/products/index', [
            'products' => $products,
            'pages' => $pages,
            'categories' => json_encode($categories),
            'currentCategory' => $currentCategory
        ]);
    }

    public function show($id)
    {
        $this->view->render('frontend/products/show', [
            'product' => Products::findById($id)
        ]);
    }

    public function addToBag($id)
    {
        if ($this->isUserLoggedIn()) {
            $currentUser = currentUser();
            $product = Products::findById($id);
            $existingOrder = Orders::query("SELECT * FROM orders WHERE user_id = ? AND product_id = ?", [$currentUser->id, $product->id])->first() ?? null;

            if ($existingOrder && $existingOrder->product_id === $product->id) {
                Orders::update(['count' => $existingOrder->count + $this->request->get('count')], $existingOrder->id);
            } else {
                (new Orders())->insert([
                    'user_id' => $currentUser->id,
                    'profile_id' => $currentUser->id,
                    'product_id' => $product->id,
                    'count' => $this->request->get('count')
                ]);
            }

            return $this->back();

        } else {
            $this->redirect('/login');
        }
    }
}

app/views/admin/products/create.php
<?php $this->setSiteTitle('Создание товара'); ?>
<?php $this->start('body'); ?>

<div class="card w-50 m-auto bg-transparent">
    <h4 class="card-header text-primary text-center">Создание товара</h4>
    <div class="card-body">
        <form class="mx-auto product" method="POST" action="<?= route('admin.products.store') ?>">
            <div class="form-group">
                <input type="text" class="form-control form-control-product" id="name" name="name" placeholder="Product name"
                       required>
            </div>
            <div class="form-group row">
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-product" id="price" name="price"
                           placeholder="Цена" required>
                </div>
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <select class="form-control" id="gender" name="gender">
                        <option value="<?= $this->genders['male'] ?>">Муж.</option>
                        <option value="<?= $this->genders['female'] ?>">Жен.</option>
                        <option value="<?= $this->genders['unisex'] ?>">Юнисекс</option>
                    </select>
                </div>
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <select class="form-control" id="category_id" name="category_id">
                        <?php foreach ($this->categories as $category): ?>
                            <option value="<?= $category->id ?>"><?= $category->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="row justify-content-center">
                <button type="submit" class="btn btn-primary btn-product btn-block w-50">
                    Создать
                </button>
            </div>
            <hr>
        </form>
    </div>
</div>

<?php $this->end(); ?>

app/views/admin/products/edit.php
<?php $this->setSiteTitle('Редактирование товара'); ?>

<?php $this->start('body'); ?>

<div class="card w-50 m-auto bg-transparent">
    <h4 class="card-header text-primary text-center">Редактировать</h4>
    <div class="card-body">
        <form class="mx-auto product" method="POST" action="<?= route('admin.products.update', $this->product->id) ?>">
            <div class="form-group">
                <input type="text" class="form-control form-control-product" id="name" name="name" placeholder="Product name"
                       required value="<?= $this->product->name ?>">
            </div>
            <div class="form-group row">
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-product" id="price" name="price"
                           placeholder="Цена" value="<?= $this->product->price ?>">
                </div>
                <div class="col-sm-4 mb-3 mb-sm-0">
                    <select class="form-control" id="gender" name="gender">
                        <option value="<?= $this->genders['male'] ?>">Муж.</option>
                        <option value="<?= $this->genders['female'] ?>">Жен.</option>
                        <option value="<?= $this->genders['unisex'] ?>">Юнисекс</option>
                    </select>
                </div>
            </div>
            <div class="row justify-content-center">
                <button type="submit" class="btn btn-primary btn-product btn-block w-50">
                    Редактировать
                </button>
            </div>
            <hr>
        </form>
    </div>
</div>

<?php $this->end(); ?>

app/views/admin/products/index.php
<?php $this->setSiteTitle('Products'); ?>

<?php $this->start('head'); ?>

<link rel="stylesheet" href="/node_modules/bstreeview/src/css/bstreeview.css">

<?php $this->end(); ?>


<?php $this->start('body'); ?>

<div class="row">
    <div class="col-md-2 pt-5">
        <div id="tree">

        </div>
    </div>
    <div class="col-md-10 pt-5">

        <?php foreach (array_chunk($this->products, 4) as $block): ?>
            <div class="row">
        <?php foreach ($block as $product): ?>
            <div class="col-sm d-flex flex-column justify-content-center align-items-center">
                <div class="card mb-3" style="width: 18rem">
                    <img src="<?php echo "/static/products/{$product->category_id}/{$product->id}/{$product->id}.jpeg"; ?>" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title text-dark text-center"><?= $product->name ?></h5>
                        <p class="card-text text-primary text-center"><?= $product->price ?> ₽</p>
                        <div class="btn-group btn-group-sm">
                            <a class="btn btn-primary m-1" href="<?= route('admin.products.show', $product->id) ?>" role="button"><small>Смотреть</small></a>
                            <a class="btn btn-warning m-1" href="<?= route('admin.products.edit', $product->id) ?>" role="button"><small>Редактировать</small></a>
                            <a class="btn btn-danger m-1" href="<?= route('admin.products.delete', $product->id) ?>" role="button"><small>Удалить</small></a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
            </div>
        <?php endforeach; ?>

        <?php if($this->pages && $this->pages->getTotalPages() > 1): ?>
        <div class="row d-flex align-items-center justify-content-center m-3">
            <?= $this->component('pagination/pagination', ['pages' => $this->pages]); ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<?php $this->end(); ?>


<?php $this->start('scripts'); ?>

<script src="/node_modules/bstreeview/src/js/bstreeview.js"></script>

<script>
    let tree = <?= $this->categories; ?>;

    $('#tree').bstreeview({
        data: tree,
        openNodeLinkOnNewTab: false
    });
</script>

<?php $this->end(); ?>

app/views/admin/products/show.php
<?php $this->setSiteTitle('Страничка товара'); ?>

<?php $this->start('body'); ?>

<div class="container d-flex justify-content-center">
    <div class="card">
        <img src="/products/coats/<?= $this->product->id . DS . $this->product->id . '.jpeg' ?>" class="card-img-top" alt="...">
        <div class="card-body text-center">
            <h5 class="card-title text-dark"><?= $this->product->name ?></h5>
            <p class="card-text text-primary"><?= $this->product->price ?> руб.</p>
            <a href="<?= route('admin.products.edit', $this->product->id) ?>" class="btn btn-primary">Редактировать</a>
        </div>
    </div>
</div>

<?php $this->end(); ?>